name: Build

on:
  push:
  pull_request:
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubicloud-standard-4

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: gumboard_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      GITHUB_CLIENT_ID: dummy-client-id
      GITHUB_CLIENT_SECRET: dummy-client-secret
      AUTH_SECRET: sample-auth-secret
      AUTH_URL: http://localhost:3000
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/gumboard_test
      EMAIL_FROM: noreply@example.com
      AUTH_RESEND_KEY: dummy-resend-key

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Set up database schema
        run: |
          npx prisma migrate deploy
          npx prisma generate

      - name: Build Next.js application
        run: npm run build

      - name: Check build output
        run: |
          if [ ! -d ".next" ]; then
            echo "Error: .next directory not found after build"
            exit 1
          fi
          echo "✅ Build completed successfully"
          echo "Build artifacts:"
          ls -la .next/
